### ISSUE TITLE
Huge download size

### ISSUE THREAD

**Issue by dpriskorn** [Kungbib/swedish-spacy#6]
I tried spaCy for English and it was a 20 MB download.  This repo seems to require a 800 MB download. Why is that?

**Comment by Nuccy90** [comment]
It depends if you refer to the version 2 or 3 models.
For version 2, the difference is because spaCy has its core models in three sizes, small, medium and large according to how many word vectors ship with the models. We decided not to prune the vectors since we were only going to publish one model and we wanted it to be as generally applicable as possible.
For version 3, we need to have two transformers instead of one inside the model package because we don't have all linguistic features annotated on the same data. 
I hope this answers your question!
